//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.UI.Xaml.Scheduler.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syncfusion_UI_Xaml_Scheduler
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_UI_Xaml_Scheduler()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.UI.Xaml.Scheduler.Resources.Syncfusion_UI_Xaml_Scheduler", typeof(Syncfusion_UI_Xaml_Scheduler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert
        {
            get
            {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Day.
        /// </summary>
        internal static string AllDay
        {
            get
            {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string April
        {
            get
            {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string August
        {
            get
            {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count
        {
            get
            {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily
        {
            get
            {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day
        {
            get
            {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        internal static string Days
        {
            get
            {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string December
        {
            get
            {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete this occurrence.
        /// </summary>
        internal static string DeleteOccurrence
        {
            get
            {
                return ResourceManager.GetString("DeleteOccurrence", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all occurence of the recurring appointment [], or just this one?.
        /// </summary>
        internal static string DeleteRecurringDialogContent
        {
            get
            {
                return ResourceManager.GetString("DeleteRecurringDialogContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string DeleteRecurringDialogHeader
        {
            get
            {
                return ResourceManager.GetString("DeleteRecurringDialogHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete this series.
        /// </summary>
        internal static string DeleteSeries
        {
            get
            {
                return ResourceManager.GetString("DeleteSeries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Event.
        /// </summary>
        internal static string EditEventTitle
        {
            get
            {
                return ResourceManager.GetString("EditEventTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is one appointment in a series. What do you want to open?.
        /// </summary>
        internal static string EditRecurringDialogContent
        {
            get
            {
                return ResourceManager.GetString("EditRecurringDialogContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Recurring Item.
        /// </summary>
        internal static string EditRecurringDialogHeader
        {
            get
            {
                return ResourceManager.GetString("EditRecurringDialogHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End
        {
            get
            {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End Timezone.
        /// </summary>
        internal static string EndTimezone
        {
            get
            {
                return ResourceManager.GetString("EndTimezone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string February
        {
            get
            {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First
        {
            get
            {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string Fourth
        {
            get
            {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday
        {
            get
            {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The end date you entered occurs before the start date..
        /// </summary>
        internal static string InValidEndTimeMessageAlert
        {
            get
            {
                return ResourceManager.GetString("InValidEndTimeMessageAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two occurrences of [] cannot occur on the same day..
        /// </summary>
        internal static string InvalidOccurrenceEditingMessageAlert
        {
            get
            {
                return ResourceManager.GetString("InvalidOccurrenceEditingMessageAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string January
        {
            get
            {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string July
        {
            get
            {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string June
        {
            get
            {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Just this one.
        /// </summary>
        internal static string JustThisOne
        {
            get
            {
                return ResourceManager.GetString("JustThisOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last
        {
            get
            {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location
        {
            get
            {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string March
        {
            get
            {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string May
        {
            get
            {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday
        {
            get
            {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly
        {
            get
            {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Month(s).
        /// </summary>
        internal static string Months
        {
            get
            {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More
        {
            get
            {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never
        {
            get
            {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        internal static string NewEvent
        {
            get
            {
                return ResourceManager.GetString("NewEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Date Selected.
        /// </summary>
        internal static string NoDateSelected
        {
            get
            {
                return ResourceManager.GetString("NoDateSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Events.
        /// </summary>
        internal static string NoEvents
        {
            get
            {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string November
        {
            get
            {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string October
        {
            get
            {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot reschedule an occurrence of the recurring appointment [] if it skips over a later occurrence of the same appointment..
        /// </summary>
        internal static string OutRangeOccurrencedEditingMessageAlert
        {
            get
            {
                return ResourceManager.GetString("OutRangeOccurrencedEditingMessageAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat
        {
            get
            {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat Every.
        /// </summary>
        internal static string RepeatEvery
        {
            get
            {
                return ResourceManager.GetString("RepeatEvery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat On.
        /// </summary>
        internal static string RepeatOn
        {
            get
            {
                return ResourceManager.GetString("RepeatOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday
        {
            get
            {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Second
        {
            get
            {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string September
        {
            get
            {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start
        {
            get
            {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Timezone.
        /// </summary>
        internal static string StartTimeZone
        {
            get
            {
                return ResourceManager.GetString("StartTimeZone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday
        {
            get
            {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The entire series.
        /// </summary>
        internal static string TheEntireSeries
        {
            get
            {
                return ResourceManager.GetString("TheEntireSeries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string Third
        {
            get
            {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday
        {
            get
            {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string TimeZone
        {
            get
            {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday
        {
            get
            {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string Until
        {
            get
            {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday
        {
            get
            {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly
        {
            get
            {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Week(s).
        /// </summary>
        internal static string Weeks
        {
            get
            {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string Yearly
        {
            get
            {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Year(s).
        /// </summary>
        internal static string Years
        {
            get
            {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
